---
title: "HW 1"
subtitle: "Data 180, Professor Bilen"
author: 
  name: "Your Name"
  email: "XXXX@dickinson.edu"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document
---
Make sure that you have accepted the hw invitation link, and working with your clone repository.

**Due date:** September 20 beginning of class.

**Reminder:** You can insert R code in your Rmd file as a chunk in the following way:
```{r}
# Your code goes here
```
Make sure to insert a chunk for each (sub)section of the assignment.

## Preliminary Task
Go to [datacamp.com](https://datacamp.com) and complete the tutorial "Introduction to R".


## Task 1
a) Store the data below in a data frame object named `my_df`.


|Person | Preference|
|:------|:----------|
|Alice | Twitter |
| Bob | Facebook |
| Charlie | Twitter |
| Denise | Instagram |
| Erin | Facebook |
| Frank | Twitter |
| Gisele | Twitter |
| Harry | Instagram |

b) What are the dimensions of `my_df`?

c) Write R code that counts the total number of users.

d) Write R code that counts the total number of users who prefer Twitter.

e) Write R code that returns what Gisele prefers.

## Task 2
a) Create a vector named `my_vec` that includes all integers from 1 to 10 (inclusive).

b) Replace the second element in `my_vec` with the number `99`.

c) Write a function called `my_func` that prints `This element is greater than 5!` if an element in `myvec` is greater than 5, and `This element is NOT greater than 5!` otherwise.

## Task 3
a. Write a function named `get_fibonacci` that returns the n'th value in the [fibonacci sequence](https://www.mathsisfun.com/numbers/fibonacci-sequence.html). For example, `get_fibonacci(5)` should return 3; `get_fibonacci(7)` should return 8 and so on. ***Hint:** It is possible to call the same function from inside it. E.g., you can call `get_fibonacci()` from inside `get_fibonacci()`. Like inception!*

b. Using your function in part (a), find and return the 19th value in the fibonacci sequence.


<br>
You are done! 🏁 Don't forget to `commit` and `push` your .Rmd file to your Github clone repository before the due date.
<br>

