---
title: "cluster"
output: html_document
date: "2023-11-07"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
df <- read.csv('https://raw.githubusercontent.com/ernbilen/Data180_Fall23/main/data/Cluster_Ex.csv')
```

```{r}
library(ggplot2)
ggplot(df,aes(x=X1,y=X2)) + 
  geom_point()
```

```{r}
plot(df$X1,df$X2)
```

```{r}
# note that the first col has row names
dist(df[,-1])
```

```{r}
# create a dendrogram
plot(hclust(dist(df[,-1],method='manhattan'), method = 'complete'))
```

```{r}
# create a dendrogram
hc_obj <- hclust(dist(df[,-1],method='manhattan'), method = 'complete')
plot(hc_obj)
rect.hclust(hc_obj,k=3,border=c('green','red','blue'))
```


```{r}
# create a new variable called assignment that shows cluster assignments of each obs
df$assignment <- factor(cutree(hclust(dist(df[,-1],method='manhattan'), method = 'complete'),k=3))
```


```{r}
library(ggplot2)
ggplot(df,aes(x=X1,y=X2,col=assignment)) + 
  geom_point(size=2)
```


```{r}
# US States arrests data
data("USArrests")
```

```{r}
# visually inspect obs from two columns in the data, Murder and Assault rates
library(ggplot2)
ggplot(USArrests,aes(x=Murder,y=Assault)) +
    geom_point(size=2)
```

```{r}
# create a dendrogram using all four variables in the data
hc_obj <- hclust(dist(USArrests,method='euclidean'), method = 'complete')
plot(hc_obj)
rect.hclust(hc_obj,k=3,border=c('green','red','blue'))

```

```{r}
# color the scatterplot separately using cluster assignments
USArrests$assignment <- factor(cutree(hclust(dist(USArrests,method='euclidean'), method = 'complete'),k=3))

ggplot(USArrests,aes(x=Murder,y=Assault,col=assignment)) +
    geom_point(size=2)
```

```{r}
#install.packages('ggdendro')
library(ggdendro)
# dendrogram using ggplot2
# load in the custom funcs
dendro_data_k <- function(hc, k) {
  
  hcdata    <-  ggdendro::dendro_data(hc, type = "rectangle")
  seg       <-  hcdata$segments
  labclust  <-  cutree(hc, k)[hc$order]
  segclust  <-  rep(0L, nrow(seg))
  heights   <-  sort(hc$height, decreasing = TRUE)
  height    <-  mean(c(heights[k], heights[k - 1L]), na.rm = TRUE)
  
  for (i in 1:k) {
    xi      <-  hcdata$labels$x[labclust == i]
    idx1    <-  seg$x    >= min(xi) & seg$x    <= max(xi)
    idx2    <-  seg$xend >= min(xi) & seg$xend <= max(xi)
    idx3    <-  seg$yend < height
    idx     <-  idx1 & idx2 & idx3
    segclust[idx] <- i
  }
  
  idx                    <-  which(segclust == 0L)
  segclust[idx]          <-  segclust[idx + 1L]
  hcdata$segments$clust  <-  segclust
  hcdata$segments$line   <-  as.integer(segclust < 1L)
  hcdata$labels$clust    <-  labclust
  
  hcdata
}


set_labels_params <- function(nbLabels,
                              direction = c("tb", "bt", "lr", "rl"),
                              fan       = FALSE) {
  if (fan) {
    angle       <-  360 / nbLabels * 1:nbLabels + 90
    idx         <-  angle >= 90 & angle <= 270
    angle[idx]  <-  angle[idx] + 180
    hjust       <-  rep(0, nbLabels)
    hjust[idx]  <-  1
  } else {
    angle       <-  rep(0, nbLabels)
    hjust       <-  0
    if (direction %in% c("tb", "bt")) { angle <- angle + 45 }
    if (direction %in% c("tb", "rl")) { hjust <- 1 }
  }
  list(angle = angle, hjust = hjust, vjust = 0.5)
}


plot_ggdendro <- function(hcdata,
                          direction   = c("lr", "rl", "tb", "bt"),
                          fan         = FALSE,
                          scale.color = NULL,
                          branch.size = 1,
                          label.size  = 3,
                          nudge.label = 0.01,
                          expand.y    = 0.1) {
  
  direction <- match.arg(direction) # if fan = FALSE
  ybreaks   <- pretty(segment(hcdata)$y, n = 5)
  ymax      <- max(segment(hcdata)$y)
  
  ## branches
  p <- ggplot() +
    geom_segment(data         =  segment(hcdata),
                 aes(x        =  x,
                     y        =  y,
                     xend     =  xend,
                     yend     =  yend,
                     linetype =  factor(line),
                     colour   =  factor(clust)),
                 lineend      =  "round",
                 show.legend  =  FALSE,
                 size         =  branch.size)
  
  ## orientation
  if (fan) {
    p <- p +
      coord_polar(direction = -1) +
      scale_x_continuous(breaks = NULL,
                         limits = c(0, nrow(label(hcdata)))) +
      scale_y_reverse(breaks = ybreaks)
  } else {
    p <- p + scale_x_continuous(breaks = NULL)
    if (direction %in% c("rl", "lr")) {
      p <- p + coord_flip()
    }
    if (direction %in% c("bt", "lr")) {
      p <- p + scale_y_reverse(breaks = ybreaks)
    } else {
      p <- p + scale_y_continuous(breaks = ybreaks)
      nudge.label <- -(nudge.label)
    }
  }
  
  # labels
  labelParams <- set_labels_params(nrow(hcdata$labels), direction, fan)
  hcdata$labels$angle <- labelParams$angle
  
  p <- p +
    geom_text(data        =  label(hcdata),
              aes(x       =  x,
                  y       =  y,
                  label   =  label,
                  colour  =  factor(clust),
                  angle   =  angle),
              vjust       =  labelParams$vjust,
              hjust       =  labelParams$hjust,
              nudge_y     =  ymax * nudge.label,
              size        =  label.size,
              show.legend =  FALSE)
  
  # colors and limits
  if (!is.null(scale.color)) {
    p <- p + scale_color_manual(values = scale.color)
  }
  
  ylim <- -round(ymax * expand.y, 1)
  p    <- p + expand_limits(y = ylim)
  
  p
}
```

```{r}
hcdata <- dendro_data_k(hc_obj,3)
plot_ggdendro(hcdata,direction='lr',fan=FALSE,expand.y = .2)
```

```{r}
library(MASS)
library(dplyr)
#data(Cars93)

# are there any clusters in the Cars93 data based on two columns: Horsepower, MPG.city?

dfcars <- Cars93[,c("Horsepower", "MPG.city", "MPG.highway","Price", "EngineSize")]
hc_cars <- hclust(dist(dfcars,method = "manhattan"), method = "complete")
plot(hc_cars)
rect.hclust(hc_cars, k=4, border = c("green", "red", "blue", "yellow"))

dfcars$assignments <- factor(cutree(hc_cars,k=4))

plot(dfcars$Horsepower,dfcars$MPG.city,col=dfcars$assignment)
```

```{r}
#vertebrate <- read.csv('https://raw.githubusercontent.com/ernbilen/Data180_Fall23/main/homework/hw5/vertebrate.csv')
#head(vertebrate)

# dendrogram with 0-0 matches not discarded
#1-dist(vertebrate,method='manhattan')/6

# dendrogram with 0-0 matches discarded
plot(hclust(1-dist(vertebrate,method='binary'),method='complete'))

```

```{r}
# Gower's measure: Daisy function (which comes from the cluster package)
# Make a dendrogram using complete-linkage method

# install.packages(cluster)

# Use: AirBag, Cylinders, Origin (discard 0-0 matches), Length, MPG.city, Horsepower
library(MASS)
data(Cars93)

```



