

```{r}
# create a vector Y that has five 3's.
#Y <- c(3,3,3,3,3)
Y <- rep(3,5)
length(Y)
```


```{r}
# sequence of numbers
seq(1,11,2)
```

```{r}
X <- c(1,2,3,4)
names(X) <- c('first','second','third','fourth')
names(X)[3] <- "THIRD"
X
```


```{r}
# shortcut to create numbers between 1 and 8
1:8
```

```{r}
X <- matrix(1:8,nrow=2,byrow = T)
#X
# row 2, col 3
#X[2,3]
# entire row 2
#X[2,]
#X[,3:4]
X
# get rid of col 2
X[,-2]
# get rid of col 2 and 4
X[,-c(2,4)]
```
```{r}
dim(X)
```

```{r}
# custom row and col names
rownames(X) <- c('first row','second row')
colnames(X) <- c('col1','col2','col3','col4')
X
```

```{r}
sqrt(X)
```

```{r}
# create a list X
X <- list(c('first row','second row'), matrix(1:8,nrow=2,byrow=T), rep(3,5))
X

# second element of the first element on the list
#X[[1:2]]
#X[[1]][2]

# return col3 from the second element on the list
X[[2]][,3]
```

```{r}
# name elements of a list
names(X) <- c('vec','mat','rep')
X
```
```{r}
X[[1]]
X$vec
```

```{r}
# Factor variables in R
Treatment <- c('Drug','Drug','Drug','Placebo','Placebo','Placebo')
# define the object Treatment, overwrite
Treatment <- factor(Treatment)
print.default(Treatment)
```
```{r}
# Factor variables in R
Treatment <- c('Drug','Drug','Drug','Placebo','Placebo','Placebo')
# define the object Treatment, overwrite
Treatment <- factor(Treatment,levels=c('Placebo','Drug'))
#print.default(Treatment)
Treatment <- as.integer(Treatment) -1
Treatment
Age <- c(17,15,25,30,5,55)
Age
my_df <- data.frame(my_Treatment=Treatment,Age)
colnames(my_df)
# return the age column in different ways
my_df$Age
my_df[,2] # the first number for row position, second for col pos
```

```{r}
Number <- c(1, 4, 2, 5)
Letter <- c('a', 'r', 'g', 'f')
Truth <- c(T, F, F, T)

demo_df <- data.frame(Number, Letter, Truth)
demo_df
```

```{r}
demo_df <- data.frame(Number=c(1,4,2,5), Letter=c('a','r','g','f'), Truth=c(T,F,F,T))
demo_df
# row 3, col 2
demo_df[3,2]
# same value, but instead uses "Letter"
demo_df$Letter[3]
# equivalent, but does not use "$"
demo_df[3,"Letter"]

# typeof() function returns the type of an object
typeof(demo_df$Number)
typeof(demo_df$Letter)
typeof(demo_df$Truth)
```

```{r}
# Functions
X<- c(1,2,3,4)
X
# returns the objects in memory
ls()

# calculate the mean of a set numbers
mean(X)
# equivalent to
(X[1]+X[2]+X[3]+X[4])/4


X[3] <- NA
X
mean(X,na.rm = T)

mean <- c(1,2,3)
mean
find('mean')
rm(mean)
find('mean')
mean

#fix(say_hi)

say_hi <- function(){
  print('Hello World!')
}

say_hi()

# conditions in R
my_number <- -5
if(my_number < 0){
  print('your number is negative!')
} else if(my_number > 0){
  print('your number is positive!')
} else {
  print('your number is zero!')
}

# create a function named my_func() that checks if a number is positive,
# negative, or zero, and prints the output
my_func <- function(number){
  if(number <0){
    print('your number is negative!')
  } else if(number>0){
    print('your number is positive!')
  } else {
      print('your number is zero!')
  }
}

my_func(0)

# create a function named bmi_calculator that takes in two inputs: weight in kg
# and height in m, and returns the bmi of a person where bmi = kg/m^2
bmi_calculator <- function(height, weight){
  return(weight/height^2) # returns the output
}
bmi_calculator(1.7, 60)

# create a function named bmi_prompt that takes in weight and kg as inputs and prints the categories for the bmi calculated
# where <18.5 is underweight
# between 18.5 and 25 is normal
# between 25 and 30 is overweight
# over 30 is obese
bmi_prompt <- function(weight, height) {
  bmi <- bmi_calculator(height,weight)
  if  (bmi<18.5) {
    print("underweight")
  } else if (18.5 <= bmi & bmi <= 25) {
    print("healthy")
  } else if (25 <= bmi & bmi <=30) {
    print("overweight")
  }
  else {
    print("obese")
  }
  return(bmi)
}

bmi_prompt(30,1.7)
```

```{r}
# for-loop
for (i in 1:3){
  print(i)
}
```

```{r}
# for loop with vector of characters
myVec <- c("R","is","fun")
for (word in myVec){
  print(word)
}
```

```{r}
# library MASS contains toy datasets
library(MASS)
# let's call the Cars93 dataset
data(Cars93)
# head() displays the first 6 rows by default
head(Cars93)

nrow(Cars93)
ncol(Cars93)

rownames(Cars93)

# returns the Price col
Cars93$Price

# returns cars with 09 < 10 and all cols
Cars93[Cars93$Price < 10,]

# returns cars with Prise < 10 and only the type col
Cars93[Cars93$Price < 10, 'Type']
```

```{r}
# import data in R
df <- read.csv('https://raw.githubusercontent.com/ernbilen/Data180_Fall23/main/data/majors.csv')
head(df)
```


