---
title: "ggplot2"
output: html_document
date: "2023-09-26"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# fits through a smooth curve
#install.packages('ggplot2')
library(ggplot2)
theme_set(theme_bw())
#data(diamonds)
#??diamonds
# scatterplot of price and carat
#plot(price~carat,data=diamonds)
ggplot(diamonds, aes(x=carat,y=price)) +
                 geom_point(col='black',alpha=.2,size=1,shape=2) +
                 labs(y='price, $',x='carat value',title='Here is a title',subtitle='Here is a subtitle', caption='Taken from X et al (202X)') +
                  geom_smooth()
```

```{r}
# transforming axes
ggplot(diamonds, aes(x=carat,y=price)) +
                 geom_point(col='black',alpha=.2,size=1,shape=1) +
                 labs(y='log of price, $',x='log of carat value',title='Here is a title',subtitle='Here is a subtitle', caption='Taken from X et al (202X)') +
        coord_trans(x='log10',y='log10')
                 
```

```{r}
# add information from a third variable (categorical)
ggplot(diamonds, aes(x=carat,y=price,col=color)) +
                 geom_point(size=1) +
                 labs(y='price, $',x='carat value',title='Here is a title',subtitle='Here is a subtitle', caption='Taken from X et al (202X)')
```

```{r}
# add information from a third variable (continuous)
ggplot(diamonds, aes(x=carat,y=price,col=table)) +
                 geom_point(size=1) +
                 labs(y='price, $',x='carat value',title='Here is a title',subtitle='Here is a subtitle', caption='Taken from X et al (202X)')
```

```{r}
# conditional plots
ggplot(diamonds, aes(x=carat,y=price)) +
                 geom_point(size=1) +
                 labs(y='price, $',x='carat value',title='Here is a title',subtitle='Here is a subtitle', caption='Taken from X et al (202X)') +
  facet_wrap(~color,nrow=1,labeller=label_both)
```

```{r}
# Make a histogram in ggplot
ggplot(diamonds,aes(depth)) +
          geom_histogram(binwidth =.2)
```

```{r}
# Make multiple histograms side by side
ggplot(diamonds,aes(depth)) +
          geom_histogram(bins=100) +
          facet_wrap(~cut,nrow=1)
```

```{r}
# Make multiple histograms in one graph
ggplot(diamonds,aes(depth,fill=cut)) +
          geom_histogram(bins=100,color='black',alpha=.4,position = 'identity')
```


```{r}
# conditional scatter plot with cars93
ggplot(Cars93, aes(x= Price, y = Horsepower, col = Origin)) +
  geom_point(size = 2) +
  labs(x = 'Price ($)', y = 'Horsepower') +
  facet_wrap(~Origin)
```

```{r}
# conditional histogram with cars93
ggplot(Cars93, aes(Price)) +
  geom_histogram(bins = 9) + 
  facet_wrap(~Type, nrow = 1) + 
  labs(title = 'Distribution of Price over Type', x = 'Price', y ='Count')
```

```{r}
# Making maps with ggplot2
#install.packages('maps')
#install.packages('sf')
library(ggplot2)
library(maps)
library(sf)
states <- map_data("state")

# just to check how many rows we have for Alabama
nrow(states[states$region == 'alabama',])

# aside
#my_vec <- 5:10
#my_vec

# first element of my_vec
#my_vec[1]

# return elements greater than 7
#my_vec[my_vec>7]

# return first row of states df
#states[1,]

# points along the border of alabama used to create the map
#ggplot(states[states$region=='alabama',], aes(x=long,y=lat)) +
#          geom_point()

ggplot(states, aes(x=long,y=lat,group=group,fill=region)) +
          geom_polygon(color='black') +
          coord_sf(crs=st_crs(4326)) +
          theme(legend.position = 'none')
```

```{r}
#install.packages('mapview') # you can get rid of this line after installation
library(mapview)
library(sf)

df_states <- st_read('/Users/bilene/Downloads/Data180_Fall23-main-3/data/us-states/us-states.shp')
#mapview(df_states) # already gives a nice map!
#mapview(df_states,zcol='population')
#mapview(df_states,zcol='population',col.regions=blues9)
mapview(df_states,zcol='population',col.regions=blues9,label=paste('State Name:',df_states$NAME,'<br>State Population',df_states$population,'<br>Avg. Age:',df_states$age))
# to hide legends: legend=FALSE
# to hides the popup when you hover your mouse around the map: label=FALSE
```

```{r}
# two interactive maps side by side
#install.packages('leafsync') # you can get rid of this line after installation
library(leafsync)

map1 <- mapview(df_states[df_states$NAME=='Pennsylvania',],zcol='population',col.regions=blues9)
map2 <- mapview(df_states[df_states$NAME=='South Carolina',],zcol='population',col.regions=blues9)

sync(map1,map2)
```
